//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misa.Web05.TQCGD2.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Misa.Web05.TQCGD2.Core.Resources.ExceptionErrorMessage", typeof(ExceptionErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phòng ban đã tồn tại.
        /// </summary>
        public static string DepartmentIdExists {
            get {
                return ResourceManager.GetString("DepartmentIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phòng ban không được trống.
        /// </summary>
        public static string DepartmentIdNull {
            get {
                return ResourceManager.GetString("DepartmentIdNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phòng ban không được trống.
        /// </summary>
        public static string DepartmentNameNull {
            get {
                return ResourceManager.GetString("DepartmentNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban không được để trống.
        /// </summary>
        public static string DepartmentNull {
            get {
                return ResourceManager.GetString("DepartmentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra với hệ thống.
        /// </summary>
        public static string DevMessage400 {
            get {
                return ResourceManager.GetString("DevMessage400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra với hệ thống.
        /// </summary>
        public static string DevMessage500 {
            get {
                return ResourceManager.GetString("DevMessage500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &amp;lt;{0}&amp;gt; không hợp lệ.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên &amp;lt;{0}&amp;gt; không hợp lệ.
        /// </summary>
        public static string FullNameInvalid {
            get {
                return ResourceManager.GetString("FullNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên không được trống.
        /// </summary>
        public static string FullNameNull {
            get {
                return ResourceManager.GetString("FullNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể tạo user_role.
        /// </summary>
        public static string InsertUserRoleFailure {
            get {
                return ResourceManager.GetString("InsertUserRoleFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vị trí  đã tồn tại.
        /// </summary>
        public static string PositionIdExists {
            get {
                return ResourceManager.GetString("PositionIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vị trí không được trống.
        /// </summary>
        public static string PositionIdNull {
            get {
                return ResourceManager.GetString("PositionIdNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên vị trí không được trống.
        /// </summary>
        public static string PositionNameNull {
            get {
                return ResourceManager.GetString("PositionNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí công việc không được để trống.
        /// </summary>
        public static string PositionNull {
            get {
                return ResourceManager.GetString("PositionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vai trò không được để trống.
        /// </summary>
        public static string RoleNull {
            get {
                return ResourceManager.GetString("RoleNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên &amp;lt;{0}&amp;gt; đã tồn tại trong hệ thống, vui lòng kiểm tra lại..
        /// </summary>
        public static string UserCodeExists {
            get {
                return ResourceManager.GetString("UserCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên &amp;lt;{0}&amp;gt; không hợp lệ.
        /// </summary>
        public static string UserCodeInvalid {
            get {
                return ResourceManager.GetString("UserCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được trống.
        /// </summary>
        public static string UserCodeNull {
            get {
                return ResourceManager.GetString("UserCodeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ.
        /// </summary>
        public static string UserMessage400 {
            get {
                return ResourceManager.GetString("UserMessage400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra với hệ thống, vui lòng thử lại sau.
        /// </summary>
        public static string UserMessage500 {
            get {
                return ResourceManager.GetString("UserMessage500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy người dùng.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
